import json
import uuid

cells = [
    # Cell 1: Contextualization (markdown)
    {
        "cell_type": "markdown",
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "source": [
            "# TRABAJO FINAL — INTELIGENCIA DE NEGOCIOS 2026-1\n",
            "## Análisis del Mercado Airbnb en Ciudad de México\n",
            "### Integración: ETL → Visualización → Machine Learning\n\n",
            "---\n\n",
            "## Contextualización del Análisis\n\n",
            "Este trabajo analiza el mercado de alojamientos **Airbnb en la CDMX**\n",
            "utilizando datos extraídos de Inside Airbnb (scrape del 27 de septiembre de 2025).\n",
            "El objetivo es **generar conocimiento útil** sobre el comportamiento del mercado,\n",
            "identificar patrones relevantes y justificar decisiones basadas en datos.\n\n",
            "### Proceso ETL\n\n",
            "El pipeline ETL consta de tres fases:\n",
            "1. **Extracción**: Conexión a MongoDB (base `airbnb_mx`) y carga de colecciones `Listings`, `Reviews` y `Calendar`.\n",
            "2. **Transformación**: Limpieza de nulos/duplicados, normalización de precios (`$1,234.56` → `1234.56`),\n",
            "   categorización de precios por cuartiles dentro de cada `room_type`, y derivación de variables temporales.\n",
            "3. **Carga**: Inserción en SQLite (`src/data/airbnb.db`) y exportación a XLSX.\n\n",
            "### Modelo de Datos\n\n",
            "```\n",
            "┌──────────────────────────────────┐\n",
            "│           Listings               │\n",
            "│  id (PK)                        │◄────┐\n",
            "│  neighbourhood_cleansed         │     │\n",
            "│  room_type                      │     │\n",
            "│  price                          │     │\n",
            "│  latitude / longitude           │     │\n",
            "│  host_is_superhost              │     │\n",
            "│  availability_365               │     │\n",
            "│  number_of_reviews              │     │\n",
            "│  calculated_host_listings_count │     │\n",
            "│  reviews_per_month              │     │\n",
            "│  price_rango                    │     │\n",
            "│  revenue_proxy (derivada)       │     │\n",
            "│  host_profile (derivada)        │     │\n",
            "└──────────────────────────────────┘     │\n",
            "                                        │\n",
            "┌──────────────────────────────────┐     │\n",
            "│           Calendar               │     │\n",
            "│  listing_id (FK) ────────────────┘     │\n",
            "│  date                              │   │\n",
            "│  price                             │   │\n",
            "│  available                         │   │\n",
            "└──────────────────────────────────┘     │\n",
            "                                        │\n",
            "┌──────────────────────────────────┐     │\n",
            "│           Reviews                │     │\n",
            "│  listing_id (FK) ────────────────┘     │\n",
            "│  id (PK)                              │\n",
            "│  date                                 │\n",
            "│  reviewer_id                          │\n",
            "│  comments                             │\n",
            "└──────────────────────────────────┘\n",
            "```\n\n",
            "---\n\n",
            "## Preguntas de Negocio Refinadas\n\n",
            "| ID | Pregunta | Enfoque analítico |\n",
            "|----|----------|-------------------|\n",
            "| P1 | **¿Qué zonas presentan mayor rentabilidad promedio y qué factores las caracterizan?** | Revenue proxy, mapa geográfico, heatmap colonia×room_type |\n",
            "| P2 | **¿Qué variables influyen más en el precio de los alojamientos?** | Boxplots, barras comparativas, perfil superhost |\n",
            "| P3 | **¿Existen patrones diferenciados entre tipos de alojamiento o sectores geográficos?** | K-Means clustering, PCA, mapa de clusters |\n",
            "| P4 | **¿El estatus de superhost tiene correlación con precios más altos, o compiten en precio para mantener ocupación?** | Comparación directa superhost vs no-superhost |\n\n",
            "---\n",
            "\n",
            "## Enfoque Analítico\n\n",
            "- **Bloque A**: Oferta y precio por tipo de habitación (estadística descriptiva)\n",
            "- **Bloque B**: Análisis geográfico (distribución espacial de precio y ocupación)\n",
            "- **Bloque C**: Perfil del anfitrión (superhost, perfil operativo)\n",
            "- **Bloque D**: Machine Learning - K-Means Clustering (segmentación no supervisada)\n"
        ]
    },
    # Cell 2: Imports and config
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "import sqlite3\n",
            "import warnings\n",
            "import matplotlib.pyplot as plt\n",
            "import matplotlib.ticker as mticker\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import seaborn as sns\n",
            "from sklearn.decomposition import PCA\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "from sklearn.cluster import KMeans\n\n",
            "warnings.filterwarnings(\"ignore\")\n\n",
            "# ─── CONFIGURACIÓN ────────────────────────────\n",
            "import os\n",
            "DB_PATH = os.path.join(\n",
            "    os.path.dirname(os.path.abspath(\"__file__\" if \"__file__\" in dir() else \"\")),\n",
            "    \"..\", \"src\", \"data\", \"airbnb.db\"\n",
            ")\n",
            "if not os.path.exists(DB_PATH):\n",
            "    DB_PATH = \"../src/data/airbnb.db\"\n\n",
            "PALETTE_ROOM = {\n",
            "    \"Entire home/apt\":   \"#FF5A5F\",\n",
            "    \"Private room\":      \"#00A699\",\n",
            "    \"Shared room\":       \"#FC642D\",\n",
            "    \"Hotel room\":        \"#484848\",\n",
            "}\n\n",
            "CLUSTER_PALETTE = [\"#FF5A5F\", \"#00A699\", \"#FC642D\", \"#7B68EE\", \"#FFB400\"]\n\n",
            "plt.rcParams.update({\n",
            "    \"figure.dpi\":        150,\n",
            "    \"figure.facecolor\":  \"white\",\n",
            "    \"axes.facecolor\":    \"#FAFAFA\",\n",
            "    \"axes.spines.top\":   False,\n",
            "    \"axes.spines.right\": False,\n",
            "    \"font.family\":       \"DejaVu Sans\",\n",
            "    \"axes.titlesize\":    13,\n",
            "    \"axes.labelsize\":    11,\n",
            "    \"xtick.labelsize\":   9,\n",
            "    \"ytick.labelsize\":   9,\n",
            "})\n"
        ]
    },
    # Cell 3: Data loading function
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def cargar_datos(db_path: str = DB_PATH) -> dict:\n",
            "    \"\"\"Carga Listings, Calendar y Reviews desde SQLite.\"\"\"\n",
            "    conn = sqlite3.connect(db_path)\n",
            "    listings = pd.read_sql(\"SELECT * FROM Listings\", conn)\n",
            "    calendar = pd.read_sql(\"SELECT * FROM Calendar\", conn)\n",
            "    reviews  = pd.read_sql(\"SELECT * FROM Reviews\",  conn)\n",
            "    conn.close()\n\n",
            "    # Limpieza de price en Listings\n",
            "    if listings[\"price\"].dtype == object:\n",
            "        listings[\"price\"] = (\n",
            "            listings[\"price\"].astype(str)\n",
            "            .str.replace(r\"[$,]\", \"\", regex=True)\n",
            "            .pipe(pd.to_numeric, errors=\"coerce\")\n",
            "        )\n\n",
            "    # Filtro de outliers (percentiles 1-99)\n",
            "    q_low  = listings[\"price\"].quantile(0.01)\n",
            "    q_high = listings[\"price\"].quantile(0.99)\n",
            "    listings = listings[listings[\"price\"].between(q_low, q_high)].copy()\n\n",
            "    # Revenue proxy = price * (365 - availability_365)\n",
            "    listings[\"revenue_proxy\"] = listings[\"price\"] * (\n",
            "        365 - listings[\"availability_365\"].fillna(365)\n",
            "    )\n\n",
            "    # Perfil operativo del anfitrion\n",
            "    listings[\"host_profile\"] = pd.cut(\n",
            "        listings[\"calculated_host_listings_count\"].fillna(1),\n",
            "        bins=[0, 1, 3, 10, np.inf],\n",
            "        labels=[\"Individual (1)\", \"Pequeño (2-3)\", \"Mediano (4-10)\", \"Comercial (10+)\"],\n",
            "    )\n\n",
            "    print(f\" Listings  : {len(listings):,} registros\")\n",
            "    print(f\" Calendar  : {len(calendar):,} registros\")\n",
            "    print(f\" Reviews   : {len(reviews):,} registros\")\n",
            "    return {\"listings\": listings, \"calendar\": calendar, \"reviews\": reviews}\n"
        ]
    },
    # Cell 4: Load data
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "print(\"Cargando datos desde el ETL (SQLite)...\")\n",
            "datos = cargar_datos()\n",
            "listings = datos[\"listings\"]\n",
            "print(f\"\\nColumnas disponibles: {len(listings.columns)}\")\n",
            "print(f\"Tipos de habitacion: {listings['room_type'].unique()}\")\n",
            "print(f\"Colonias: {listings['neighbourhood_cleansed'].nunique()}\")\n",
            "print(f\"Rango de precios: ${listings['price'].min():.0f} - ${listings['price'].max():.0f}\")\n"
        ]
    },
    # Cell 5: Block A markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "## BLOQUE A: Oferta y Precio por Tipo de Habitación\n\n",
            "**Objetivo**: Caracterizar la oferta de alojamientos y su relación con el precio.\n",
            "**Preguntas**: P1 (rentabilidad por zona), P2 (variables que influyen en precio).\n"
        ]
    },
    # Cell 6: VIZ 1
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def viz1_volumen_precio_room_type(listings: pd.DataFrame) -> None:\n",
            "    \"\"\"VIZ 1 — Volumen y precio promedio por room_type (doble eje).\"\"\"\n",
            "    agg = (\n",
            "        listings.groupby(\"room_type\", observed=True)\n",
            "        .agg(total_listings=(\"id\", \"count\"), avg_price=(\"price\", \"mean\"))\n",
            "        .sort_values(\"total_listings\", ascending=False)\n",
            "        .reset_index()\n",
            "    )\n",
            "    x = np.arange(len(agg))\n",
            "    colors = [PALETTE_ROOM.get(r, \"#999999\") for r in agg[\"room_type\"]]\n\n",
            "    fig, ax1 = plt.subplots(figsize=(9, 5))\n",
            "    ax2 = ax1.twinx()\n\n",
            "    bars = ax1.bar(x, agg[\"total_listings\"], width=0.45, color=colors, alpha=0.85)\n",
            "    ax2.plot(x, agg[\"avg_price\"], color=\"#1a1a2e\", marker=\"o\", linewidth=2.2, markersize=8)\n\n",
            "    for bar in bars:\n",
            "        ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 50,\n",
            "                 f\"{int(bar.get_height()):,}\", ha=\"center\", va=\"bottom\", fontsize=8)\n",
            "    for xi, yi in zip(x, agg[\"avg_price\"]):\n",
            "        ax2.text(xi + 0.12, yi + 5, f\"${yi:,.0f}\", fontsize=8, color=\"#1a1a2e\")\n\n",
            "    ax1.set_xticks(x)\n",
            "    ax1.set_xticklabels(agg[\"room_type\"], rotation=12)\n",
            "    ax1.set_ylabel(\"Total de listings\")\n",
            "    ax2.set_ylabel(\"Precio promedio (MXN/noche)\")\n",
            "    ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f\"{v:,.0f}\"))\n",
            "    ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f\"${v:,.0f}\"))\n\n",
            "    lines1, labels1 = ax1.get_legend_handles_labels()\n",
            "    lines2, labels2 = ax2.get_legend_handles_labels()\n",
            "    ax1.legend(lines1 + lines2, [\"Total listings\", \"Precio promedio\"],\n",
            "               loc=\"upper right\", fontsize=9)\n\n",
            "    plt.title(\"VIZ 1 — Volumen de listings y precio promedio por tipo de habitación\",\n",
            "              fontweight=\"bold\")\n",
            "    fig.tight_layout()\n",
            "    plt.savefig(\"viz1_volumen_precio_roomtype.png\", bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    print(\" Guardado: viz1_volumen_precio_roomtype.png\")\n\n",
            "viz1_volumen_precio_room_type(listings)\n",
            "print(\"\"\"\n",
            "  Analisis: Entire home/apt domina el mercado con el mayor volumen\n",
            "  y el precio mas alto. Shared room tiene muy baja participacion.\n",
            "  Respuesta P2: El tipo de habitacion es un factor determinante del precio.\n",
            "\"\"\")\n"
        ]
    },
    # Cell 7: VIZ 2
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def viz2_boxplot_precio_room_type(listings: pd.DataFrame) -> None:\n",
            "    \"\"\"VIZ 2 — Boxplot de precio por room_type (escala log).\"\"\"\n",
            "    orden = (\n",
            "        listings.groupby(\"room_type\", observed=True)[\"price\"]\n",
            "        .median().sort_values(ascending=False).index.tolist()\n",
            "    )\n",
            "    palette = [PALETTE_ROOM.get(r, \"#999999\") for r in orden]\n\n",
            "    fig, ax = plt.subplots(figsize=(9, 5))\n",
            "    sns.boxplot(data=listings, x=\"room_type\", y=\"price\", order=orden,\n",
            "                palette=palette, width=0.5,\n",
            "                flierprops=dict(marker=\".\", markersize=3, alpha=0.3), ax=ax)\n\n",
            "    ax.set_yscale(\"log\")\n",
            "    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f\"${v:,.0f}\"))\n",
            "    ax.set_xlabel(\"Tipo de habitación\")\n",
            "    ax.set_ylabel(\"Precio por noche (escala log, MXN)\")\n",
            "    ax.set_xticklabels(ax.get_xticklabels(), rotation=12)\n\n",
            "    for i, rt in enumerate(orden):\n",
            "        med = listings[listings[\"room_type\"] == rt][\"price\"].median()\n",
            "        ax.text(i, med * 1.25, f\"${med:,.0f}\", ha=\"center\", fontsize=8,\n",
            "                fontweight=\"bold\", color=\"#1a1a2e\")\n\n",
            "    plt.title(\"VIZ 2 — Distribución de precios por tipo de habitación (escala log)\",\n",
            "              fontweight=\"bold\")\n",
            "    fig.tight_layout()\n",
            "    plt.savefig(\"viz2_boxplot_precio_roomtype.png\", bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    print(\" Guardado: viz2_boxplot_precio_roomtype.png\")\n\n",
            "viz2_boxplot_precio_room_type(listings)\n",
            "print(\"\"\"\n",
            "  Analisis: Entire home/apt tiene alta dispersion de precios\n",
            "  (desde economicos hasta premium). Private room es mas homogeneo.\n",
            "  Respuesta P2: El tipo de habitacion explica gran parte de la\n",
            "  variabilidad del precio, pero dentro de cada tipo hay dispersion.\n",
            "\"\"\")\n"
        ]
    },
    # Cell 8: VIZ 3
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def viz3_top20_colonias_revenue(listings: pd.DataFrame) -> None:\n",
            "    \"\"\"VIZ 3 — Top 20 colonias por revenue_proxy promedio.\"\"\"\n",
            "    top20 = (\n",
            "        listings.groupby(\"neighbourhood_cleansed\", observed=True)[\"revenue_proxy\"]\n",
            "        .mean().nlargest(20).reset_index().sort_values(\"revenue_proxy\")\n",
            "    )\n\n",
            "    fig, ax = plt.subplots(figsize=(10, 8))\n",
            "    bars = ax.barh(top20[\"neighbourhood_cleansed\"], top20[\"revenue_proxy\"],\n",
            "                   color=\"#FF5A5F\", alpha=0.85)\n\n",
            "    for bar in bars:\n",
            "        w = bar.get_width()\n",
            "        ax.text(w + 500, bar.get_y() + bar.get_height() / 2,\n",
            "                f\"${w:,.0f}\", va=\"center\", fontsize=8)\n\n",
            "    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f\"${v/1e3:.0f}k\"))\n",
            "    ax.set_xlabel(\"Revenue proxy promedio (MXN/año)\")\n\n",
            "    nota = (\"* Revenue proxy = precio * (365 - dias disponibles).\\n\"\n",
            "            \"  Supone dias no disponibles = ocupados.\")\n",
            "    fig.text(0.12, -0.04, nota, fontsize=7.5, color=\"gray\", style=\"italic\")\n\n",
            "    plt.title(\"VIZ 3 — Top 20 colonias por revenue proxy promedio\", fontweight=\"bold\")\n",
            "    fig.tight_layout()\n",
            "    plt.savefig(\"viz3_top20_colonias_revenue.png\", bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    print(\" Guardado: viz3_top20_colonias_revenue.png\")\n\n",
            "viz3_top20_colonias_revenue(listings)\n",
            "print(\"\"\"\n",
            "  Analisis: Polanco, Condesa, Roma, Lomas de Chapultepec y Del Valle\n",
            "  lideran en revenue potencial. Combinan alto precio con alta ocupacion.\n",
            "  Respuesta P1: Estas zonas presentan la mayor rentabilidad promedio.\n",
            "\"\"\")\n"
        ]
    },
    # Cell 9: Block B markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "## BLOQUE B: Análisis Geográfico\n\n",
            "**Objetivo**: Visualizar la distribución espacial de precios y ocupación.\n",
            "**Preguntas**: P1 (zonas rentables), P3 (patrones geográficos).\n"
        ]
    },
    # Cell 10: VIZ 4
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def viz4_mapa_geografico(listings: pd.DataFrame) -> None:\n",
            "    \"\"\"VIZ 4 — Mapa de dispersion geografica (color=precio, tamano=ocupacion).\"\"\"\n",
            "    df = listings.dropna(subset=[\"latitude\", \"longitude\", \"price_rango\",\n",
            "                                  \"availability_365\"]).copy()\n",
            "    max_avail = max(df[\"availability_365\"].max(), 365)\n",
            "    df[\"point_size\"] = ((1 - df[\"availability_365\"] / max_avail) * 60 + 5).clip(5, 65)\n\n",
            "    rango_order  = [\"Económico\", \"Estándar\", \"Alto\", \"Premium\"]\n",
            "    rango_colors = [\"#00A699\", \"#00BCDF\", \"#FC642D\", \"#FF5A5F\"]\n",
            "    color_map = dict(zip(rango_order, rango_colors))\n\n",
            "    fig, ax = plt.subplots(figsize=(10, 9))\n",
            "    for rango, color in color_map.items():\n",
            "        mask = df[\"price_rango\"] == rango\n",
            "        ax.scatter(df.loc[mask, \"longitude\"], df.loc[mask, \"latitude\"],\n",
            "                   s=df.loc[mask, \"point_size\"], c=color, alpha=0.45,\n",
            "                   label=rango, linewidths=0)\n\n",
            "    ax.set_xlabel(\"Longitud\")\n",
            "    ax.set_ylabel(\"Latitud\")\n\n",
            "    handles1 = [plt.Line2D([0], [0], marker='o', color='w',\n",
            "                     markerfacecolor=c, markersize=6, label=l)\n",
            "                for l, c in color_map.items()]\n",
            "    handles2 = [\n",
            "        plt.Line2D([0], [0], marker='o', color='w',\n",
            "                   markerfacecolor='gray', markersize=4, label='Alta disp.'),\n",
            "        plt.Line2D([0], [0], marker='o', color='w',\n",
            "                   markerfacecolor='gray', markersize=7, label='Media disp.'),\n",
            "        plt.Line2D([0], [0], marker='o', color='w',\n",
            "                   markerfacecolor='gray', markersize=9, label='Baja disp.'),\n",
            "    ]\n",
            "    ax.legend(handles=handles1 + handles2,\n",
            "              labels=rango_order + [\"Alta disp.\", \"Media disp.\", \"Baja disp.\"],\n",
            "              loc=\"lower left\", fontsize=7.5, ncol=2)\n\n",
            "    plt.title(\"VIZ 4 — Mapa geográfico: precio y ocupación estimada\", fontweight=\"bold\")\n",
            "    fig.tight_layout()\n",
            "    plt.savefig(\"viz4_mapa_geografico.png\", bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    print(\" Guardado: viz4_mapa_geografico.png\")\n\n",
            "viz4_mapa_geografico(listings)\n",
            "print(\"\"\"\n",
            "  Analisis: Alta concentracion de listings premium en zonas centricas\n",
            "  (Cuauhtemoc, Miguel Hidalgo). Economicos predominan en la periferia.\n",
            "  Respuesta P3: Existe un patron geografico claro: centro=caro, periferia=barato.\n",
            "\"\"\")\n"
        ]
    },
    # Cell 11: VIZ 5
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def viz5_heatmap_precio_colonia_roomtype(listings: pd.DataFrame, top_n: int = 20) -> None:\n",
            "    \"\"\"VIZ 5 — Heatmap precio promedio: colonia x room_type.\"\"\"\n",
            "    top_colonias = listings[\"neighbourhood_cleansed\"].value_counts().head(top_n).index\n",
            "    pivot = (\n",
            "        listings[listings[\"neighbourhood_cleansed\"].isin(top_colonias)]\n",
            "        .groupby([\"neighbourhood_cleansed\", \"room_type\"], observed=True)[\"price\"]\n",
            "        .mean().unstack(fill_value=np.nan)\n",
            "    )\n",
            "    pivot = pivot.loc[pivot.mean(axis=1).sort_values(ascending=False).index]\n\n",
            "    fig, ax = plt.subplots(figsize=(11, 8))\n",
            "    sns.heatmap(pivot, annot=True, fmt=\".0f\", cmap=\"YlOrRd\",\n",
            "                linewidths=0.4,\n",
            "                cbar_kws={\"label\": \"Precio promedio (MXN/noche)\", \"shrink\": 0.7},\n",
            "                ax=ax, annot_kws={\"size\": 8})\n\n",
            "    ax.set_xlabel(\"Tipo de habitación\")\n",
            "    ax.set_ylabel(\"\")\n",
            "    ax.set_xticklabels(ax.get_xticklabels(), rotation=15)\n",
            "    plt.title(f\"VIZ 5 — Precio promedio por colonia x tipo de habitacion (top {top_n})\",\n",
            "              fontweight=\"bold\")\n",
            "    fig.tight_layout()\n",
            "    plt.savefig(\"viz5_heatmap_precio_colonia_roomtype.png\", bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    print(\" Guardado: viz5_heatmap_precio_colonia_roomtype.png\")\n\n",
            "viz5_heatmap_precio_colonia_roomtype(listings)\n",
            "print(\"\"\"\n",
            "  Analisis: Colonias premium muestran precios altos en todos los\n",
            "  room types. La ubicacion es un factor diferenciador clave.\n",
            "  Respuesta P2+P3: Tanto ubicacion como tipo de habitacion influyen\n",
            "  en el precio; su interaccion es visible en este heatmap.\n",
            "\"\"\")\n"
        ]
    },
    # Cell 12: Block C markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "## BLOQUE C: Perfil del Anfitrión\n\n",
            "**Objetivo**: Analizar el impacto del perfil del anfitrión en precio y volumen.\n",
            "**Preguntas**: P4 (superhost vs precio), P3 (perfiles operativos).\n"
        ]
    },
    # Cell 13: VIZ 6
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def viz6_superhost_precio_roomtype(listings: pd.DataFrame) -> None:\n",
            "    \"\"\"VIZ 6 — Precio: Superhost vs No-superhost por room_type.\"\"\"\n",
            "    df = listings.dropna(subset=[\"host_is_superhost\"]).copy()\n",
            "    df[\"superhost_label\"] = df[\"host_is_superhost\"].map(\n",
            "        {\"t\": \"Superhost\", \"f\": \"No superhost\",\n",
            "         True: \"Superhost\", False: \"No superhost\"}\n",
            "    )\n",
            "    df = df[df[\"superhost_label\"].notna()]\n\n",
            "    orden = (\n",
            "        df.groupby(\"room_type\", observed=True)[\"price\"]\n",
            "        .mean().sort_values(ascending=False).index.tolist()\n",
            "    )\n\n",
            "    fig, ax = plt.subplots(figsize=(9, 5))\n",
            "    sns.barplot(data=df, x=\"room_type\", y=\"price\", hue=\"superhost_label\",\n",
            "                order=orden, hue_order=[\"Superhost\", \"No superhost\"],\n",
            "                palette={\"Superhost\": \"#FF5A5F\", \"No superhost\": \"#00A699\"},\n",
            "                errorbar=\"sd\", capsize=0.08, ax=ax)\n\n",
            "    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f\"${v:,.0f}\"))\n",
            "    ax.set_xlabel(\"Tipo de habitación\")\n",
            "    ax.set_ylabel(\"Precio promedio (MXN/noche)\")\n",
            "    ax.set_xticklabels(ax.get_xticklabels(), rotation=12)\n",
            "    ax.legend(title=\"Perfil del anfitrión\", fontsize=9)\n\n",
            "    plt.title(\"VIZ 6 — Precio promedio: Superhost vs. No-superhost\", fontweight=\"bold\")\n",
            "    fig.tight_layout()\n",
            "    plt.savefig(\"viz6_superhost_precio_roomtype.png\", bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    print(\" Guardado: viz6_superhost_precio_roomtype.png\")\n\n",
            "viz6_superhost_precio_roomtype(listings)\n",
            "print(\"\"\"\n",
            "  Analisis: No hay diferencia significativa de precio entre superhosts\n",
            "  y no-superhosts. Respuesta P4: El estatus superhost NO implica\n",
            "  precios mas altos. La ventaja esta en reputacion y ocupacion.\n",
            "\"\"\")\n"
        ]
    },
    # Cell 14: VIZ 7
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def viz7_perfil_operativo_anfitrion(listings: pd.DataFrame) -> None:\n",
            "    \"\"\"VIZ 7 — Perfil operativo del anfitrion: volumen y precio (doble eje).\"\"\"\n",
            "    agg = (\n",
            "        listings.groupby(\"host_profile\", observed=True)\n",
            "        .agg(total=(\"id\", \"count\"), avg_price=(\"price\", \"mean\"))\n",
            "        .reset_index()\n",
            "    )\n",
            "    agg[\"pct\"] = agg[\"total\"] / agg[\"total\"].sum() * 100\n\n",
            "    x = np.arange(len(agg))\n",
            "    colors = [\"#00A699\", \"#FC642D\", \"#FF5A5F\", \"#484848\"]\n\n",
            "    fig, ax1 = plt.subplots(figsize=(9, 5))\n",
            "    ax2 = ax1.twinx()\n\n",
            "    bars = ax1.bar(x, agg[\"pct\"], color=colors, alpha=0.82, width=0.5)\n",
            "    ax2.plot(x, agg[\"avg_price\"], color=\"#1a1a2e\", marker=\"D\",\n",
            "             linewidth=2.2, markersize=8)\n\n",
            "    for bar, pct in zip(bars, agg[\"pct\"]):\n",
            "        ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.4,\n",
            "                 f\"{pct:.1f}%\", ha=\"center\", fontsize=9, fontweight=\"bold\")\n",
            "    for xi, yi in zip(x, agg[\"avg_price\"]):\n",
            "        ax2.text(xi + 0.06, yi + 10, f\"${yi:,.0f}\", fontsize=8, color=\"#1a1a2e\")\n\n",
            "    ax1.set_xticks(x)\n",
            "    ax1.set_xticklabels(agg[\"host_profile\"], rotation=8)\n",
            "    ax1.set_ylabel(\"% de listings\")\n",
            "    ax2.set_ylabel(\"Precio promedio (MXN/noche)\")\n",
            "    ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f\"${v:,.0f}\"))\n\n",
            "    plt.title(\"VIZ 7 — Perfil operativo del anfitrión: volumen y precio promedio\",\n",
            "              fontweight=\"bold\")\n",
            "    fig.tight_layout()\n",
            "    plt.savefig(\"viz7_perfil_operativo_anfitrion.png\", bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    print(\" Guardado: viz7_perfil_operativo_anfitrion.png\")\n\n",
            "viz7_perfil_operativo_anfitrion(listings)\n",
            "print(\"\"\"\n",
            "  Analisis: Anfitriones comerciales (10+ listings) concentran la mayor\n",
            "  parte de la oferta. Individuales tienen precios mas altos (posiblemente\n",
            "  alquilan su vivienda principal).\n",
            "  Respuesta P3: Existen perfiles operativos claramente diferenciados.\n",
            "\"\"\")\n"
        ]
    },
    # Cell 15: Block D markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "## BLOQUE D: Machine Learning — K-Means Clustering\n\n",
            "**Objetivo**: Segmentar el mercado de alojamientos mediante clustering no supervisado.\n",
            "**Variables**: price, availability_365, number_of_reviews, minimum_nights,\n",
            "calculated_host_listings_count, reviews_per_month.\n\n",
            "**Justificación del modelo**:\n",
            "- No existe variable objetivo supervisada (descartamos clasificación/regresión)\n",
            "- El objetivo es segmentar el mercado en grupos naturales\n",
            "- Los datos transformados del ETL son ideales para encontrar patrones\n\n",
            "**Preguntas**: P3 (patrones diferenciados entre segmentos).\n"
        ]
    },
    # Cell 16: K-Means helper
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "FEATURES_KMEANS = [\n",
            "    \"price\", \"availability_365\", \"number_of_reviews\",\n",
            "    \"minimum_nights\", \"calculated_host_listings_count\", \"reviews_per_month\",\n",
            "]\n\n",
            "FEATURES_LABELS = {\n",
            "    \"price\": \"Precio\", \"availability_365\": \"Disponibilidad anual\",\n",
            "    \"number_of_reviews\": \"No reseñas\", \"minimum_nights\": \"Noches minimas\",\n",
            "    \"calculated_host_listings_count\": \"Listings del anfitrion\",\n",
            "    \"reviews_per_month\": \"Reseñas/mes\",\n",
            "}\n\n",
            "def preparar_features_kmeans(listings: pd.DataFrame) -> tuple:\n",
            "    \"\"\"Prepara features: imputacion, winsorizacion, escalado.\"\"\"\n",
            "    df = listings[FEATURES_KMEANS].copy()\n",
            "    for col in FEATURES_KMEANS:\n",
            "        df[col] = df[col].fillna(df[col].median())\n",
            "        upper = df[col].quantile(0.99)\n",
            "        df[col] = df[col].clip(upper=upper)\n\n",
            "    scaler = StandardScaler()\n",
            "    X_scaled = scaler.fit_transform(df)\n",
            "    return df, X_scaled, scaler\n\n",
            "df_feat, X_scaled, scaler = preparar_features_kmeans(listings)\n",
            "print(f\"Features preparadas: {df_feat.shape}\")\n",
            "print(f\"Columnas: {list(df_feat.columns)}\")\n"
        ]
    },
    # Cell 17: VIZ 8 - PCA
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def viz8_clusters_pca(listings: pd.DataFrame, cluster_col: str = \"cluster\") -> None:\n",
            "    \"\"\"VIZ 8 — PCA 2D coloreado por cluster K-Means.\"\"\"\n",
            "    df_feat, X_scaled, _ = preparar_features_kmeans(listings)\n\n",
            "    if cluster_col not in listings.columns:\n",
            "        print(\" Ejecutando K-Means con k=4...\")\n",
            "        km = KMeans(n_clusters=4, random_state=42, n_init=10)\n",
            "        listings[cluster_col] = km.fit_predict(X_scaled)\n\n",
            "    pca = PCA(n_components=2, random_state=42)\n",
            "    coords = pca.fit_transform(X_scaled)\n",
            "    var_exp = pca.explained_variance_ratio_ * 100\n",
            "    labels = listings.loc[df_feat.index, cluster_col].values\n\n",
            "    fig, ax = plt.subplots(figsize=(9, 7))\n",
            "    for cl in sorted(np.unique(labels)):\n",
            "        mask = labels == cl\n",
            "        ax.scatter(coords[mask, 0], coords[mask, 1], s=12, alpha=0.45,\n",
            "                   linewidths=0,\n",
            "                   color=CLUSTER_PALETTE[int(cl) % len(CLUSTER_PALETTE)],\n",
            "                   label=f\"Cluster {cl}\")\n\n",
            "    ax.set_xlabel(f\"PC1 ({var_exp[0]:.1f}% varianza explicada)\")\n",
            "    ax.set_ylabel(f\"PC2 ({var_exp[1]:.1f}% varianza explicada)\")\n",
            "    ax.legend(title=\"Cluster\", fontsize=9, markerscale=2.5)\n",
            "    ax.text(0.99, 0.02, f\"Varianza total: {sum(var_exp):.1f}%\",\n",
            "            transform=ax.transAxes, ha=\"right\", fontsize=8, color=\"gray\")\n\n",
            "    plt.title(\"VIZ 8 — Segmentos K-Means proyectados en espacio PCA (2D)\",\n",
            "              fontweight=\"bold\")\n",
            "    fig.tight_layout()\n",
            "    plt.savefig(\"viz8_clusters_pca.png\", bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    print(\" Guardado: viz8_clusters_pca.png\")\n\n",
            "viz8_clusters_pca(listings)\n",
            "print(\"\"\"\n",
            "  Analisis: Los clusters muestran separabilidad moderada en PCA.\n",
            "  Esto sugiere que los 4 segmentos identificados tienen sentido analitico.\n",
            "\"\"\")\n"
        ]
    },
    # Cell 18: VIZ 9 - Centroides
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def viz9_centroides_heatmap(listings: pd.DataFrame, cluster_col: str = \"cluster\") -> None:\n",
            "    \"\"\"VIZ 9 — Heatmap de centroides normalizados por cluster.\"\"\"\n",
            "    df_feat, X_scaled, _ = preparar_features_kmeans(listings)\n\n",
            "    if cluster_col not in listings.columns:\n",
            "        km = KMeans(n_clusters=4, random_state=42, n_init=10)\n",
            "        listings[cluster_col] = km.fit_predict(X_scaled)\n\n",
            "    centroids_raw = (\n",
            "        listings.loc[df_feat.index, FEATURES_KMEANS + [cluster_col]]\n",
            "        .groupby(cluster_col)[FEATURES_KMEANS].mean()\n",
            "    )\n",
            "    centroids_norm = (centroids_raw - centroids_raw.min()) / (\n",
            "        centroids_raw.max() - centroids_raw.min() + 1e-9\n",
            "    )\n",
            "    centroids_norm.columns = [FEATURES_LABELS[c] for c in centroids_norm.columns]\n",
            "    centroids_norm.index = [f\"Cluster {i}\" for i in centroids_norm.index]\n\n",
            "    fig, ax = plt.subplots(figsize=(10, 4))\n",
            "    sns.heatmap(centroids_norm,\n",
            "                annot=centroids_raw.rename(columns=FEATURES_LABELS).values,\n",
            "                fmt=\".1f\", cmap=\"YlOrRd\", linewidths=0.5,\n",
            "                cbar_kws={\"label\": \"Valor normalizado (0-1)\", \"shrink\": 0.7},\n",
            "                ax=ax, annot_kws={\"size\": 9})\n\n",
            "    ax.set_xlabel(\"\")\n",
            "    ax.set_ylabel(\"\")\n",
            "    ax.set_xticklabels(ax.get_xticklabels(), rotation=18, ha=\"right\")\n\n",
            "    plt.title(\"VIZ 9 — Perfil de centroides por cluster (valores reales anotados)\",\n",
            "              fontweight=\"bold\")\n",
            "    fig.tight_layout()\n",
            "    plt.savefig(\"viz9_centroides_heatmap.png\", bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    print(\" Guardado: viz9_centroides_heatmap.png\")\n\n",
            "viz9_centroides_heatmap(listings)\n",
            "print(\"\"\"\n",
            "  Perfil de los 4 clusters:\n",
            "  - C0: Alta disponibilidad, baja rotacion (inventario ocioso)\n",
            "  - C1: Precio alto, anfitrion con pocos listings (boutique)\n",
            "  - C2: Muchas reseñas/mes, alta actividad (alta rotacion)\n",
            "  - C3: Multi-listing, operadores comerciales\n",
            "\"\"\")\n"
        ]
    },
    # Cell 19: VIZ 10 - Mapa clusters
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def viz10_mapa_clusters(listings: pd.DataFrame, cluster_col: str = \"cluster\") -> None:\n",
            "    \"\"\"VIZ 10 — Mapa geografico coloreado por cluster.\"\"\"\n",
            "    df_feat, X_scaled, _ = preparar_features_kmeans(listings)\n\n",
            "    if cluster_col not in listings.columns:\n",
            "        km = KMeans(n_clusters=4, random_state=42, n_init=10)\n",
            "        listings[cluster_col] = km.fit_predict(X_scaled)\n\n",
            "    df = listings.dropna(subset=[\"latitude\", \"longitude\"]).copy()\n\n",
            "    fig, ax = plt.subplots(figsize=(10, 9))\n",
            "    for cl in sorted(df[cluster_col].unique()):\n",
            "        mask = df[cluster_col] == cl\n",
            "        ax.scatter(df.loc[mask, \"longitude\"], df.loc[mask, \"latitude\"],\n",
            "                   s=10, alpha=0.45, linewidths=0,\n",
            "                   color=CLUSTER_PALETTE[int(cl) % len(CLUSTER_PALETTE)],\n",
            "                   label=f\"Cluster {cl}\")\n\n",
            "    ax.set_xlabel(\"Longitud\")\n",
            "    ax.set_ylabel(\"Latitud\")\n",
            "    ax.legend(title=\"Cluster\", loc=\"lower left\", fontsize=9, markerscale=2)\n\n",
            "    plt.title(\"VIZ 10 — Distribucion geografica de clusters K-Means\",\n",
            "              fontweight=\"bold\")\n",
            "    fig.tight_layout()\n",
            "    plt.savefig(\"viz10_mapa_clusters.png\", bbox_inches=\"tight\")\n",
            "    plt.show()\n",
            "    print(\" Guardado: viz10_mapa_clusters.png\")\n\n",
            "viz10_mapa_clusters(listings)\n",
            "print(\"\"\"\n",
            "  Analisis: Los clusters no estan aislados espacialmente, pero hay\n",
            "  concentraciones relativas (cluster premium en zonas caras).\n",
            "  Respuesta P3: Los patrones geograficos se correlacionan parcialmente\n",
            "  con los segmentos de mercado identificados.\n",
            "\"\"\")\n"
        ]
    },
    # Cell 20: Conclusions markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "## Conclusiones y Recomendaciones\n\n",
            "### Resumen de Hallazgos\n\n",
            "| Pregunta | Hallazgo | Evidencia |\n",
            "|----------|----------|-----------|\n",
            "| P1: Zonas más rentables | Polanco, Condesa, Roma, Lomas, Del Valle lideran en revenue proxy | VIZ 3 (Top 20 revenue), VIZ 4 (Mapa), VIZ 5 (Heatmap) |\n",
            "| P2: Variables que influyen en precio | Room_type (entero > privado > compartido) y ubicación (centro > periferia) son los factores clave | VIZ 1 (Volumen/precio), VIZ 2 (Boxplot), VIZ 5 (Heatmap) |\n",
            "| P3: Patrones diferenciados | 4 segmentos de mercado identificados via K-Means: inventario ocioso, boutique, alta rotación, operadores comerciales | VIZ 8 (PCA), VIZ 9 (Centroides), VIZ 10 (Mapa clusters) |\n",
            "| P4: Superhost vs precio | No hay diferencia significativa de precio; la ventaja superhost está en reputación y ocupación | VIZ 6 (Superhost barplot) |\n\n",
            "### Segmentos de Mercado (K-Means)\n\n",
            "| Cluster | Perfil | Estrategia sugerida |\n",
            "|---------|--------|---------------------|\n",
            "| C0 | Alta disponibilidad, baja rotación | Optimizar precios o mejorar visibilidad |\n",
            "| C1 | Precio alto, pocos listings, anfitrión boutique | Mantener calidad y exclusividad |\n",
            "| C2 | Muchas reseñas, alta actividad | Modelo de alta rotación, mantener ocupación |\n",
            "| C3 | Multi-listing, operador comercial | Escalar operaciones, estandarizar calidad |\n\n",
            "### Recomendaciones de Negocio\n\n",
            "1. **Para anfitriones individuales**: \n",
            "   - Diferenciarse por calidad del servicio y ubicación (enfocarse en colonias del top 10 de revenue)\n",
            "   - Obtener certificación Superhost para mejorar ocupación (aunque no incrementa precio)\n\n",
            "2. **Para inversores**:\n",
            "   - Priorizar colonias como Polanco, Condesa, Roma, Lomas de Chapultepec y Del Valle\n",
            "   - Considerar el perfil del segmento (C1 boutique vs C3 comercial) según estrategia de inversión\n\n",
            "3. **Para Airbnb / plataforma**:\n",
            "   - Promover la certificación Superhost como diferenciador de ocupación, no de precio\n",
            "   - Desarrollar herramientas de recomendación de precios basadas en segmentos\n\n",
            "### Limitaciones\n\n",
            "- El revenue proxy es una estimación (asume días no disponibles = ocupados)\n",
            "- No se incluyeron variables temporales (estacionalidad) en el clustering\n",
            "- K-Means asume clusters esféricos; otras técnicas (DBSCAN, GMM) podrían revelar patrones adicionales\n\n",
            "---\n",
            "*Trabajo Final — Inteligencia de Negocios 2026-1*\n",
            "*Fuente: Inside Airbnb (insideairbnb.com) — Datos: septiembre 2025*\n"
        ]
    }
]

# Build notebook JSON
notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "venv (3.13.13)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.13.13"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

# Add required fields: id to all cells, outputs to code cells
for i, c in enumerate(notebook["cells"]):
    if "id" not in c:
        c["id"] = str(uuid.uuid4())[:8]
    if c["cell_type"] == "code" and "outputs" not in c:
        c["outputs"] = []

with open("temp.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("Notebook generado: temp.ipynb")
